/* eslint no-use-before-define: 0 */  // --> OFF
interface Charity {
    charityLegalName: string;
    imageURL?: string;
    smallDescription: string | any;
    longDescription?: string | any;
    addressLine1: string;
    townCity?: string;
    state: string;
    homelessness?: boolean;
    health?: boolean;
    country: string;
    charityWebsite: string;
    education?: boolean;
    chronicIllness?: boolean;
    disabilities?: boolean;
    unemployment?: boolean;
    veterans?: boolean;
    postcode: number;
  }
  
  
  export interface CharityData extends Charity {
    abn: number;
    territoryNSW: boolean;
    territoryACT: boolean;
    territoryNT: boolean;
    territoryQLD: boolean;
    territorySA: boolean;
    territoryTAS: boolean;
    territoryVIC: boolean;
    territoryWA: boolean;
  }
  
  export const australian_charities: CharityData[] = [
    //TODO: Put mongodb data here
    {
        abn: 84001797511,
        charityLegalName: 'Access Industries For The Disabled Ltd',
        imageURL: 'http://www.accessindustries.com.au/wp-content/uploads/2016/04/New_Access_logo.png',
        smallDescription:
            'We are a registered charitable organization providing employment services\u00a0for people with disabilities, otherwise known as an Australian Disability Enterprise (ADE).',
        longDescription:
            'We are a registered charitable organization providing employment services for people with disabilities, otherwise known as an Australian Disability Enterprise (ADE). The organization was originally set up by a group of people with physical disabilities back in 1949 as a self-help group for people within the community whose disabilities were not due to war service. As such, it is one of the oldest organizations of its type now operating in Australia. Today, Access Industries provides supported employment opportunities for close to 250 people with disabilities in ADE\u2019s located at Seven Hills, Erskine Park and Horsley Park in the Sydney Metropolitan Area, Hamilton (Newcastle), and Lithgow. The total number of employees is circa 500. Access Industries provides a supportive and professional workplace that creates opportunities for people with disabilities achieve economic and community participation through meaningful employment. All employees of Access Industries receive training and support to deliver quality products for our customers. As part of its commitment to providing quality services, Access Industries employs skilled Training Officers and Welfare Officers to provide or organise additional training and support for its supported employees (i.e. employees who have a disability). This enables supported employees to optimise their work potential and personal skills, and for those wishing to do so, helps to prepare them to move on into open employment.',
        addressLine1: '131 Station Rd',
        townCity: 'Seven Hills',
        state: 'New South Wales',
        postcode: 2147,
        country: 'Australia',
        charityWebsite: 'www.accessindustries.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 99804795393,
        charityLegalName: 'Arts Project Australia Inc',
        imageURL: 'https://www.artsproject.org.au/',
        smallDescription:
            'We are a creative social enterprise that supports artists with intellectual disabilities, promotes their work and advocates for their inclusion in contemporary art practice. ',
        longDescription:
            'Arts Project Australia has aimed high since 1974 when we set out to lead and innovate in the arts and disability sectors. Since then, the quality of our exhibitions and artwork created in our studio has flourished, fed by a range of innovative programs and activities. We were the first full-time art studio in Australia for artists with an intellectual disability and have built a reputation both in Australia and internationally for our achievements on this front. Proof lies in the consistency and quality of the exhibitions and programs that we produce and deliver, along with the extraordinary opportunities and experiences we have brokered for our artists. They have been included in exhibitions all over the world and are represented in countless public and private collections.',
        addressLine1: '24 High St',
        townCity: 'Northcote',
        state: 'Victoria',
        postcode: 3070,
        country: 'Australia',
        charityWebsite: 'www.artsproject.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 91530248271,
        charityLegalName: 'Blue Mountains Food Services Inc',
        imageURL:
            'https://static.wixstatic.com/media/cf0c32_926b273fa50c4cd9bbfc2e01e3edaa70~mv2.png/v1/fill/w_348,h_75,al_c,q_85,usm_0.66_1.00_0.01/cf0c32_926b273fa50c4cd9bbfc2e01e3edaa70~mv2.webp',
        smallDescription:
            "Whether it's nutritious meals delivered to your home, a friendly chat at one of our many community restaurants, or assistance with daily activities from one of our lovely volunteers, we're all about helping you to remain independent and socially connected in your community.",
        longDescription:
            'Blue Mountains Food Services (BMFS) is a not-for-profit organization which provides a range of programs and services to residents of the Blue Mountains. These include aged care services, disability services, volunteering opportunities, a social enterprise caf\u00e9 and more. We are a proud member of the NSW Meals on Wheels association and a registered NDIS provider, with over 20 years experience in the community, disability and hospitality sector. Our services focus on meeting the nutritional needs of our clients whilst addressing the issue of social isolation by engaging clients in social activity and inclusion.',
        addressLine1: '25 Livingstone St',
        townCity: 'Lawson',
        state: 'New South Wales',
        postcode: 2783,
        country: 'Australia',
        charityWebsite: 'www.bmfs.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 63201477650,
        charityLegalName: 'Boneham Aged Care Services Inc',
        imageURL: 'https://www.boneham.org/wp-content/uploads/2013/09/boneham-logo.jpg',
        smallDescription:
            'Delivering excellence in aged care services that meet or exceed the needs and expectations of our residents and clients.',
        longDescription:
            'Boneham Aged Care Services is located in Millicent, in the South East of South Australia. Just 50 kilometres from Mount Gambier, Millicent is situated in the Limestone Coast region, approximately half way between Adelaide and Melbourne. We are a community based, not-for-profit organization managed by an elected Board of Governance comprising of community members. The board, together with the General Manager/Director of Care, is responsible for the ongoing management and planning of Mary Cecelia Hart Court, a residential Aged Care facility for 90 aged persons and Boneham Cottages which comprises 25 Independent Living Units. The independent living units are located in a village setting and Mary Cecelia Hart Court is a beautiful, contemporary facility staffed by committed and competent people, who ensure that our residents\u2019 care needs are met.  We have secure areas and an ongoing relationship with Alzheimers\u2019 Australia to enable us to respond to the specific requirements of those residents with Dementia. Mary Cecelia Hart Court is a fully accredited hostel providing Ageing in Place for its residents, with qualified staff on duty 24 hours per day. In the interests of health and safety, Mary Cecelia Hart Court has a \u2018no smoking policy\u2019. Smoking is not permitted in any buildings or on the grounds.',
        addressLine1: '82 Williams Road',
        townCity: 'Millicent',
        state: 'SA',
        postcode: 5280,
        country: 'Australia',
        charityWebsite: 'www.boneham.org',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 20061257725,
        charityLegalName: 'Carers Queensland Limited',
        imageURL: 'https://carersqld.com.au/wp-content/themes/carersqld/images/logo.png',
        smallDescription:
            'With one in every eight Australians caring for a family member or friend, Carers Queensland is committed to providing specialised carer, aged, and disability support services.',
        longDescription:
            'Carers Queensland is the peak body representing unpaid family and community carers in Queensland. We respond to the unique and changing needs of the 474,000 carers across the state and those they care for. Carers Queensland started as the Queensland Council of Carers and established its head office in Camp Hill, Brisbane in 1989. Since then, we have given carers a voice. We champion equal rights and opportunities. We focus on providing support services to caring families based on what they need.',
        addressLine1: '15 Abbott St',
        townCity: 'Camp Hill',
        state: 'Queensland',
        postcode: 4152,
        country: 'Australia',
        charityWebsite: 'http://carersqld.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 12345691733,
        charityLegalName: 'CFN Association Inc.',
        imageURL: 'https://cfn.org.au/wp-content/uploads/2018/09/cropped-CFN-Logo-b.png',
        smallDescription:
            'We have a long history providing disability services within this region, and working with people with disability to  their individual goals, with support from us, their families and support networks along thereach way.',
        longDescription:
            'CFN works in partnership with individuals and families to provide tailored experiences and person-centered practices, to help the individuals we work with to thrive, inspire new opportunities, live well and dream big towards a better future. We\u2019ve always been about making positive change happen by supporting people with disabilities in Caboolture, the Sunshine Coast and Brisbane to lead the lives they choose through the range of disability services we offer. \n',
        addressLine1: '10 Grant Rd',
        townCity: 'Morayfield',
        state: 'Queensland',
        postcode: 4506,
        country: 'Australia',
        charityWebsite: 'www.cfn.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 93056378299,
        charityLegalName: 'Connectability Australia Limited',
        imageURL: 'https://www.connectability.org.au/wp-content/uploads/2019/03/connect-ability-logo_04.png',
        smallDescription:
            'ConnectAbility Australia was founded in 1992 by a group of community members and families to meet the needs of people with significant disabilities to provide opportunities to access community based resources, aged care support, facilities, disability support and family counselling.',
        longDescription:
            'In 2015, a decision was made to diversify and grow the organization to provide supports and opportunities to other groups within the community and a merger between ConnectAbility and Jesmond Connected Communities was completed. We now provide a broad range of personalised supports to older community members, children and young people and people with disabilities. ConnectAbility customers reside throughout Newcastle, Lake Macquarie, Port Stephens, Maitland and other Lower Hunter local government areas. Our approach is personal, flexible and centred on the person. Whether you are attending one of our Friendship Groups as an older person, a playgroup, community education sessions, or are a person with a disability looking to achieve goals and dreams ConnectAbility will work with you and, should you choose, those closest to you to ensure you achieve your goals.',
        addressLine1: '26 Warabrook Bvd',
        townCity: 'Warabrook',
        state: 'New South Wales',
        postcode: 2304,
        country: 'Australia',
        charityWebsite: 'www.connectabilityaus.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 71168476100,
        charityLegalName: 'Disability Matters Inc',
        imageURL: 'https://disabilitymatters.org.au/images/logo.png',
        smallDescription:
            'Disability Matters is a local, leading disability services provider with over 25 years\u2019 experience in supporting people with a disability in the Atherton Tablelands region.',
        longDescription:
            'Disability Matters has been working actively in the community to provide help and understanding with quality disability support care since 1990. Formed in response to community need, the organization was originally known as Tableland Respite Care Association. The name was changed in May 2016 to better communicate what the organization is all about \u2013 Disability Matters to us. Disability Matters operates from Heraghty House at 39 Robert St, Atherton. The building was officially opened in October 2015 and has been named in honour of Pat Heraghty who was a founding member of the Board and involved with the organization for many years. The building has office space, meeting and interview rooms. Our large meeting room is available for hire and is used by other local organizations for training sessions and seminars.',
        addressLine1: '39 Robert St',
        townCity: 'Atherton',
        state: 'QLD',
        postcode: 4883,
        country: 'Australia',
        charityWebsite: 'www.disabilitymatters.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 83058123729,
        charityLegalName: 'Fairhaven Services Ltd',
        imageURL: 'https://www.fairhaven.org.au/wp-content/uploads/2018/03/fairhaven_logo.png',
        smallDescription:
            'We are a social enterprise established to ensure that people living with disability on the Central Coast live the lives that they aspire to, with a commitment to providing community participation, social skills, employment opportunities, accommodation and living supports.',
        longDescription:
            'Fairhaven is a not for profit organization that began as a school in 1962, formed by a group of Central Coast parents who came together with a single goal: to provide education options for their children with intellectual disabilities who were unable to access mainstream schools. We are a social enterprise established to ensure that people living with disability on the Central Coast live the lives that they aspire to, with a commitment to providing community participation, social skills, employment opportunities, accommodation and living supports. Fairhaven provides accommodation and care at Kincumber and Ettalong, giving people with disabilities independence and offering full time carers assistance and respite. We provide accommodation and community support across the Central Coast. We also operate the Supported Employment Enterprise (SEE) business divisions at Fairhaven CoPack in Tuggerah, and an upcycling re-use hub, Fairhaven ReCreate at Point Clare. Community support is essential to our operations. We always welcome donations and volunteers.',
        addressLine1: '209 Brisbane Water Dr',
        townCity: 'Point Clare',
        state: 'New South Wales',
        postcode: 2250,
        country: 'Australia',
        charityWebsite: 'http://www.fairhaven.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 70712994485,
        charityLegalName: 'Lismore Home Modification Service Inc',
        imageURL:
            'https://static.wixstatic.com/media/3f85de_8a12e259d8344d489bc1e743d2111ab3~mv2.jpg/v1/fill/w_225,h_128,al_c,q_80,usm_0.66_1.00_0.01/3f85de_8a12e259d8344d489bc1e743d2111ab3~mv2.webp',
        smallDescription:
            'Lismore Home Modification Service Inc is a trusted, long established organization, serving the local Lismore community and surrounding villages since 1990.\n\n \n\nOur team of staff, Builders, Tradespeople and Occupational Therapists are here to ensure your home is modified and maintained to ensure your continued safety and wellbeing.',
        longDescription:
            'HMS provides modification and minor maintenance services to eligible frail, older people and younger people with disabilities and their carers living in the Lismore and surrounding villages\u2019 local government areas. LHMS is a not for profit organization managed by a Management Committee, is registered as a Public Benevolent Institution Charity and is an Incorporated Association under the Fair Trading Act. We deliver quality services, maximising independence and wellbeing. We are committed to safety, privacy, respect, compassion and excellence. People who need assistance with daily living tasks to remain living independently at home and in the community are eligible.',
        addressLine1: '43 Habib Dr',
        townCity: 'South Lismore',
        state: 'New South Wales',
        postcode: 2480,
        country: 'Australia',
        charityWebsite: 'www.lismorehomemodification.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 79817156681,
        charityLegalName: 'Mandurah Retirement Village',
        imageURL: 'https://www.coolibah.org.au/wp-content/uploads/2018/06/cc-nav-logo2x.png',
        smallDescription:
            'To improve the lives of older people and those needing additional support in the Peel region, through the provision of high quality services that promote inclusion, engagement and independence',
        longDescription:
            'On the 15th January 1969, a group of local residents convened to discuss the lack of aged care services in the Peel community. At the time, people requiring aged care often relocated out of the homes and community they loved in order to gain help or be closer to the care they required. The group committed to building a local aged care facility so residents could remain in the community they loved with the choices and supports they required. A Board of Directors formed, appointing Mr. Owen Tuckey as Chairperson. Mr. Tuckey and Mrs. Judith Tuckey very generously donated two acres of land on which to construct the facility. Beginning with just fifteen Independent Living units, Mandurah Retirement Village Inc. was founded. Further development of the site steadily occurred over the following years as the organization expanded into all areas of aged care, including Home-Care, Serviced Independent Living Apartments, Residential Care and Day Club and Respite Care. Fifty years later, Mandurah Retirement Village Inc., now known as Coolibah, remains the leading provider of choice and support in aged care in the Peel region. Major development and re-development is ongoing, the latest update being a complete refurbishment of Coolibah Plus Serviced Apartments. The Coolibah Board, Management and Team are extremely proud to be a significant part of the Peel community history. Our commitment to our local people and community underpins everything we continue to do as we look to the future. We very much look forward to serving you for the next 50 plus years.',
        addressLine1: 'Coolibah Aged Care',
        townCity: 'Mandurah',
        state: 'Western Australia',
        postcode: 6210,
        country: 'Australia',
        charityWebsite: 'www.coolibah.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 45071386957,
        charityLegalName: 'Midway Community Care',
        imageURL: 'http://www.midwaycc.com.au/wp-content/uploads/midwaycclogobanner-1.png',
        smallDescription:
            'Midway supports people with disability to live empowered fulfilling lives in an inclusive Peel community.',
        longDescription:
            'Midway Community Care (Midway) has been providing support services to individuals with a disability in the Peel Region for over 25 years. These services include accommodation, respite brokerage support, alternatives to employment/post school options, residential respite & family support. First incorporated in December 1987, by a small group of parents concerned with a lack of services in the Peel Region. Midway was the first in the district to offer a range of services for people with a disability and their families. Midway focuses on the provision of high quality individualised services. Midway has actively lobbied for an increased variety of services within the Peel Region in order to ensure that there is a broad range of choice for people with a disability. To provide a range of innovative services for each person and their families to provide a quality of life that assists to fulfil each individual\u2019s hopes, dreams and aspirations. ',
        addressLine1: '6 Galbraith Loop',
        townCity: 'Falcon',
        state: 'Western Australia',
        postcode: 6210,
        country: 'Australia',
        charityWebsite: 'http://www.midwaycc.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 34210703350,
        charityLegalName: 'Mirridong Services Inc',
        imageURL:
            'https://www.mirridong.com.au/uploads/1/2/2/0/122030303/published/ms-horizlogo-cmyk-small-for-documents.jpg?1543960362',
        smallDescription:
            'Mirridong Services provides a diverse range of quality disability support, learning and community options which are based on best practice. ',
        longDescription: true,
        addressLine1: '6-12 Church Rd',
        townCity: 'Yarram',
        state: 'Victoria',
        postcode: 3971,
        country: 'Australia',
        charityWebsite: 'www.mirridong.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 72733048258,
        charityLegalName: 'Mosaic Support Services (Tas) inc',
        imageURL:
            'https://static1.squarespace.com/static/5c5ba8b7d74562c7485a456c/t/5d2e71596b0e7300010a462e/1585876267236/?format=1500w',
        smallDescription:
            'At Mosaic Support Services we live our Mission of enriching and improving the lives of people with a disability and their families by providing a range of quality, tailored programs. These include a myriad of Community Access, Life Skills and Training Programs. ',
        longDescription:
            'At Mosaic Support Services we live our Mission of enriching and improving the lives of people with a disability and their families by providing a suite of quality tailored programs. Including: Supported Independent Living; Emergency and Planned Respite; a myriad of Community Access, Life Skills and Training programs. We also provide a range of bespoke programs for school aged children including Camps, School Holiday Activities, After School Options and Social Time Programs. At Mosaic Support Services living our Values enables us to attract and retain high quality employees who in turn enact our Vision to enable our clients to Live Life My Way.',
        addressLine1: '99 Bathurst St',
        townCity: 'Hobart',
        state: 'Tasmania',
        postcode: 7000,
        country: 'Australia',
        charityWebsite: 'https://mosaictas.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 94253356513,
        charityLegalName: 'Nova Employment Limited',
        imageURL: 'https://www.novaemployment.com.au/images/logoNovaFront3.jpg',
        smallDescription:
            'NOVA is a Competitive Integrated Employment (CIE) Program that offers specialist job seeking assistance and post placement support. We find jobs in the general community, at award wage. ',
        longDescription:
            "Each year NOVA assists many hundreds of people to enter the workforce. To do this we find, train and provide material support to dozens of staff. This costs a lot of money and NOVA funding from the Australian Government to carry this work out however, there is still enormous unmet need. In 2002, NOVA began a formal program of fundraising. We now receive more than $100,000 annually in donations and goods. Our sponsors range from the very large (our genuine thanks to Mr. Gates and Microsoft) to the very small - annual membership of NOVA's association costs $3. The cost of taking a person with an intellectual disability, finding suitable employment and providing appropriate post-placement support is approximately $7000. Every little bit helps. ",
        addressLine1: 'Po Box 795',
        townCity: 'St Marys',
        state: 'New South Wales',
        postcode: 1790,
        country: 'Australia',
        charityWebsite: 'https://www.novaemployment.com.au/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 92154673793,
        charityLegalName: 'Primary and Community Care Services Limited',
        imageURL: 'https://pccs.org.au/wp-content/uploads/2020/02/PCCS-accentlogo.png',
        smallDescription:
            'Primary & Community Care Services (PCCS) is a local health organization working to make it easier for people to access the health and community services they need. It\u2019s about creating a smoother journey for everyone, including the people who deliver health and community services.',
        longDescription:
            "To ensure local consumer and community health needs are being met, PCCS\u2019 operations are guided by the following strategies.\n\n1. Delivering local solutions that improve outcomes and reduce costs\n\nHow we'll achieve this: As a provider of psychosocial care coordination, PCCS delivers innovative solutions to community healthcare problems with the aim of better patient care and more effective use of available and new resources.\n\nWe do this by providing the highest level and quality of psychosocial expertise and coordination for people living with severe mental illness and complex needs.\n\n2. Promoting whole of person care and integrated wrap-around care\n\nHow we'll achieve this: PCCS sees the consumer as central and advocates for care to be coordinated. PCCS joins the dots for patient care, reaching out to healthcare professionals, health and social welfare organizations and community groups to integrate services for people with specialised needs.\n\nWe provide specialist support coordination, which includes advanced support, individual assessment by a nurse, higher intensity needs, and assistance to access social activities.\n\n3. Strengthening local community linkages to foster social inclusion\n\nHow we'll achieve this: PCCS\u2019 focus is to improve the health and wellbeing of local communities through increased collaboration, integration, inclusion, research and the provision of targeted services.\n\nWe work in partnership with a range of government, community and not-for-profit organizations to provide care coordination for people living with severe mental illness.\n\n4. Creating sustainability through diversified services and partnerships\n\nHow we'll achieve this: PCCS acts as a conduit between GPs and allied health professionals, primary healthcare facilities and their patients, through its highly skilled and diverse workforce.\n\n5. Optimising the operation of health and social service systems\n\nHow we'll achieve this: PCCS operates as a change agent, inspiring better patient care through stronger integration of health and social services.",
        addressLine1: 'U 7 1 Central Ave',
        townCity: 'Thornleigh',
        state: 'New South Wales',
        postcode: 2120,
        country: 'Australia',
        charityWebsite: 'https://pccs.org.au/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 82184838127,
        charityLegalName: 'The Central Highlands And Western Qld Family Support Association',
        imageURL: 'https://yumbabimbi.com.au/wp-content/uploads/2017/12/logo-trans.png',
        smallDescription:
            'Our mission is to strengthen choice and life opportunities in an open and inclusive community.',
        longDescription:
            'Yumba Bimbi Support Services was founded in the late 1990\u2019s by a small group of progressive parents who had a vision and wanted to increase professional and local support options for people with disabilities in rural and remote communities. Since then, Yumba Bimbi Support Services has been enhancing the lives of children and adults with disabilities across the communities of the Central Highlands, Bowen Basin, and Western Queensland regions. Yumba Bimbi is a local indigenous term meaning \u201cGood Home\u201d.  Here, our dedicated team work with people who have a disability, their families, friends, and community to create a good home, good life and support a brighter future. Today, Yumba Bimbi offers a wide range of services through person-centered active support, that creates choice, opportunities and skills for life. We provide short-term accommodation (respite),  supported independent living,  assistance with daily living and life skills support, community access employment and education support, and so much more.  Yumba Bimbi operates on the premise that everyone\u2019s needs, preferences, and aspirations are different. Our commitment to client choice and family inclusion is well demonstrated through our individualised services, and person-centered principles. Our aim is to provide people with disability the chance to live, work, and play valued roles within in their community, as independently as possible.',
        addressLine1: '65 Anakie Street',
        townCity: 'Emerald',
        state: 'QLD',
        postcode: 4720,
        country: 'Australia',
        charityWebsite: 'http://www.yumbabimbi.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 75002556872,
        charityLegalName: 'The Mary Potter Nursing Home And The Ethel Forrest Day Care Centre Pty Limited',
        imageURL:
            'https://static1.squarespace.com/static/5a08c5f549fc2b1d7ba6d776/t/5a0a38ea9140b7f3b7eaf5ca/1585893080860/?format=1500w',
        smallDescription: true,
        longDescription:
            'For the past 40 years, The Forrest Centre has been part of the social fabric of Wagga Wagga. The origins of The Forrest Centre traces back to two generous and determined women \u2013 The Venerable Mary Potter, who founded the Little Company of Mary (LCM) in England, and Wagga Wagga resident Miss Ethel Forrest. Considered by many to be an eccentric recluse, Miss Forrest lived much of her life in frugal simplicity. When she died in 1977, she left the bulk of her large estate to the Anglican Diocese of Canberra and Goulburn, for the establishment of a a hospital-like facility in the region. At the same time, the Little Company of Mary had expressed intent to construct a nursing home to operate in conjunction with Calvary Hospital. The then Regional Director of health negotiated to combine theses visions which saw construction of a 60-bed nursing home, assessment and rehabilitation and day care centre for the aged community of Wagga Wagga, 1985. Today, The Forrest Centre employs more than 250 staff, comprises two residential Aged Care facilities \u2013 Mary Potter Nursing Home and Loreto Home of Compassion \u2013 in Wagga Wagga and provides at-home care services to more than 550 customers throughout the Wagga Wagga, Tumut, Leeton, Griffith and Albury-Wodonga areas.',
        addressLine1: '5 Lewisham Ave',
        townCity: 'Wagga Wagga',
        state: 'New South Wales',
        postcode: 2650,
        country: 'Australia',
        charityWebsite: 'www.forrestcentre.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 45639506303,
        charityLegalName: 'Townsville Independence Program For Adult Community Living',
        imageURL: 'http://tipacl.com.au/wp-content/uploads/2018/11/TIPACL_WP_Banner.png',
        smallDescription:
            'TIPACL aims to assist people to meet the challenges of everyday life by providing excellence in service. We are dedicated to the highest quality of service delivered with a sense of warmth, friendliness, individual pride and spirit.',
        longDescription:
            'TIPACL Inc has been operating in Townsville since 1987. We are a small local community organization that supports people with disability in a way that reflects their individual needs and lifestyles. TIPACL was originally sponsored by James Cook University. We were established in response to an urgent need for services for five young adults with severe and profound disabilities and high support needs. TIPACL has evolved over the years into a developmental service where we are committed to working with participants and their families in individualised programs where the majority of support is one-to-one. Lifestyle Support Workers support participants in accessing the community and integration into recreational, vocational and educational activities. We also assist people living in their own homes, attending appointments and developing their life skills.',
        addressLine1: 'U 1 38 Rendle St',
        townCity: 'Aitkenvale',
        state: 'Queensland',
        postcode: 4814,
        country: 'Australia',
        charityWebsite: 'tipacl.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 38129529040,
        charityLegalName: 'Transcare Hunter Limited',
        imageURL: 'https://www.transcare.org.au/wp-content/uploads/2015/04/transcare-web-logo.png',
        smallDescription:
            'We strive to provide quality community transport, in-home assistance and community wellbeing services for our clients across the Upper Hunter.',
        longDescription:
            'TransCare Hunter Limited was originally called Upper Hunter Community Care and commenced operations in November 1988. The first steering committee meeting was held in Murrurundi as Upper Hunter Community Services Group and under that group were Upper Hunter Community Transport, Upper Hunter Neighbour Aid and Peerlink. Subsequently, Peerlink branched off and Upper Hunter Community Transport and Upper Hunter Neighbour Aid merged and began trading as Upper Hunter Community Care from the 1st of July 2001. In July 2008, the legal status of Upper Hunter Community Care changed from an incorporated body to a company limited by guarantee and at the time it was decided to also change the name to TransCare Hunter Limited. At the time, TransCare\u2019s office was located in the old Scone Advocate building at 196 Kelly Street Scone. In 2011, TransCare received a generous bequest from the late Syd and Percy Barwick which was used to purchase the former Scone Library building at 214 Kelly Street from the Upper Hunter Shire Council. TransCare obtaining funding from the Department of Families and Community Services, as well as a loan, to renovate the building in order to make it suitable for TransCare\u2019s purposes. This building was named Barwick House in recognition of the donation from the Barwick brothers. Today, TransCare provides a range of community services to people who reside in the Muswellbrook Shire Council and Upper Hunter Shire Council areas. TransCare\u2019s mission is to provide quality community transport, in-home assistance and community wellbeing services for our clients across the Upper Hunter.',
        addressLine1: '214 Kelly St',
        townCity: 'Scone',
        state: 'New South Wales',
        postcode: 2337,
        country: 'Australia',
        charityWebsite: 'www.transcare.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 38096625231,
        charityLegalName: 'Australian Bone Marrow Donor Registry',
        imageURL: 'https://www.abmdr.org.au/wp-content/uploads/2016/02/logo-1.jpg',
        smallDescription:
            'We are the only organization responsible for the recruitment of volunteer bone marrow/blood stem cell donors and the administrative management of the National Cord Blood Collection Network of public cord blood banks in Australia.',
        longDescription:
            'We give patients a chance of life. Bone marrow and umbilical cord blood transplants are an option for the medical treatment of patients with blood and immune disorders. We facilitate the search for donors on behalf of patients in need of transplants. We search for suitably matched donors and umbilical cord blood units. We provide guidelines for the search, collection and care of the donor before and after the donation. We coordinate financial assistance for Australian patients. The ABMDR coordinates financial assistance provided by the Australian government for Australian patients searching for a suitable donor. We educate the community. The ABMDR raises awareness about the importance of becoming a bone marrow donor or donating umbilical cord blood. When a person joins the registry, that person joins more than 20 million people around the world who are willing to help anyone in need. We support research. We provide to the scientific community access to the ABMDR tissue repository and donors for research, managed through the ABMDR Research Governance Committee.',
        addressLine1: "17 O'riordan St",
        townCity: 'Alexandria',
        state: 'New South Wales',
        postcode: 2015,
        country: 'Australia',
        charityWebsite: 'abmdr.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 64141539442,
        charityLegalName: 'Baptist Care Northern Territory',
        imageURL: 'https://bcnt.org.au/wp-content/uploads/2017/07/logo-white.png',
        smallDescription:
            "Baptist Care NT exists to express God's love and we aim to do this by meeting people's needs, whether they be social, emotional, physical or spiritual.",
        longDescription:
            'Baptist Care Northern Territory (BCNT) was formed in 2009 as an initiative of Baptist churches in Darwin. Though a separate entity, BCNT exists as an integral ministry and priority of its member churches, in association with the Baptist Union of the NT (BUNT). BCNT is a member of Baptist Care Australia (BCA). Through our largest program, Foodbank NT (FBNT), we work with Foodbank Australia (FBA). Consequently, BCNT will seek to align its mission and vision with these organizations, where applicable. We provide a range of services including direct food support for struggling individuals and families, programs to encourage self-sufficiency and community development, and advocacy assistance. This is achieved in partnership with the churches where possible, and the wider community where appropriate.',
        addressLine1: '9 Mel Rd',
        townCity: 'Berrimah',
        state: 'Northern Territory',
        postcode: 828,
        country: 'Australia',
        charityWebsite: 'www.bcnt.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 36140829394,
        charityLegalName: 'Byron Aged Care Limited',
        imageURL: 'http://byronagedcare.com.au/wp-content/uploads/BYRON-AGED-CARE-LOGO-jpeg.jpg',
        smallDescription:
            'Byron Aged Care is a community based not for profit organization governed by a voluntary Board of Directors. The day to day running of the Home is entrusted to the Director of Care.',
        longDescription:
            'In the late 1960\u2019s a group of Byron Bay citizens, initiated by a local, George Feros, could see the need for an aged care facility to serve the Byron Bay district. An association was formed and they proceeded to acquire a suitable site, register as a charitable organization and commenced to raise funds. The great bulk of funds was provided by the association through community fund raising. In 1969 the drawing up of plans was commissioned with the brief that the building was to be above the then accepted standards, be climate friendly and provide a home-like environment for residents. Construction of the first stage, (a ten bed wing with ancillary services), was completed and opened in 1972. In 1982 the first of several additions was completed, followed by further additions in subsequent years to bring the total accommodation to the present forty one residents. The construction of the first two stages was assisted by Commonwealth construction subsidies. Since then all extensions and upgrades have been financed by the facility. The organization was originally known as the Australian Orthodox Home for the Aged Association. This later became an Incorporated Association and as our assets grew this was changed to a Company Limited by Guarantee along with the name change to Byron Aged Care Limited. Byron Aged Care is a non-profit, community-based, non-denominational facility fully accredited by the Australian Aged Care Quality Agency and strives to maintain the highest standards of service and quality of life for its residents.',
        addressLine1: '1 Butler St',
        townCity: 'Byron Bay',
        state: 'New South Wales',
        postcode: 2481,
        country: 'Australia',
        charityWebsite: 'byronagedcare.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 15190821561,
        charityLegalName: 'Cancer Council Of Western Australia (Inc)',
        imageURL: 'https://www.cancerwa.asn.au/art/CCWA-logo-digital.png',
        smallDescription:
            'Cancer Council Western Australia is WA\u2019s leading cancer charity working across every aspect of every cancer. Currently, one in two Australians will be diagnosed with cancer in their lifetime. In WA alone, there are almost 12,000 new cases of cancer diagnosed each year.',
        longDescription:
            "Cancer Council Western Australia was established in 1958 by a committed group of individuals who saw the need to coordinate cancer detection and treatment, stimulate cancer research and provide support to those affected by cancer. While many other cancer groups have since formed in WA, we have endured as Western Australia's leading independent cancer organization. We've come a long way since our humble beginnings in 1958 and we owe that to the generosity and unwavering support of the WA community. 60 years ago, the chance of surviving a cancer diagnosis was around 30 to 40 per cent. Today, survival rates for the most common cancers are more than 90 per cent, and the overall five-year survival rate for those diagnosed with cancer is around 60 per cent. With the support of the WA community, we will continue to work tirelessly to get closer to a cancer free future.",
        addressLine1: '420 Bagot Rd',
        townCity: 'Subiaco',
        state: 'Western Australia',
        postcode: 6008,
        country: 'Australia',
        charityWebsite: 'www.cancerwa.asn.au/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 67110865560,
        charityLegalName: 'Cittamani Hospice Service Limited',
        imageURL: 'https://www.cittamanihospice.com.au/sunshine/wp-content/uploads/2016/07/cittamani-logo-big.png',
        smallDescription:
            'The staff and volunteers of Cittamani support people at the end of life. They can assist you to live out your life in the way you wish and to remain at home in comfort knowing you will have 24/7 support available at the end of the phone.',
        longDescription:
            'Cittamani Hospice Service provides professional palliative care to people who are dying and their families. We offer compassionate care and honour clients\u2019 individual choices. We aim to provide the highest quality service from the time of diagnosis through to the bereavement period. Our belief is that this service is best provided in a healthy and supportive community where death, dying and bereavement are openly discussed and accepted. The promotion of healthy dying requires terminally ill adults and children to have a choice in where and how they spend their remaining life. To support this choice a range of inpatient and community services are required to ensure continuity of care. The availability of knowledgeable networks of community members is vital to the success of this process.',
        addressLine1: '230 Woombye-palmwoods Rd',
        townCity: 'Palmwoods',
        state: 'Queensland',
        postcode: 4555,
        country: 'Australia',
        charityWebsite: 'www.cittamanihospice.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 62740350704,
        charityLegalName: 'Cure For MND Foundation',
        imageURL: 'https://fightmnd.org.au/wp-content/uploads/2018/05/logo.png',
        smallDescription:
            'Founded in 2014, FightMND was established with the purpose of finding effective treatments and ultimately a cure for Motor Neurone Disease.',
        longDescription:
            'As one of the three core objectives of FightMND, Care for those Australians living with MND today is a key priority of the foundation. We are proud to support the purchase and provision of Care equipment to the state authorities and medical organizations around Australia supporting people living with MND. In 2017/2018, a total of $1.25 million was committed to FightMND Care Initiative Grants and awarded to nine organizations around Australia. FightMND is currently assessing priorities for future FightMND Care Initiative Grants and will update key stakeholders on completion of this strategic work. The 2017/2018 FightMND Care Grants exclusively funded items which fall into the categories of Augmentative and Alternative Communication (AAC) Devices or Respiratory Care-related devices. The focus of this funding was based on the considerable disparity of funding and access to these items across Australia. There is evidence that these items significantly improve both quality of life in people with MND.  ',
        addressLine1: 'Po Box 23390',
        townCity: 'Docklands',
        state: 'Victoria',
        postcode: 8012,
        country: 'Australia',
        charityWebsite: 'fightmnd.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 89304710474,
        charityLegalName: 'FareShare Australia Incorporated',
        imageURL: 'https://www.fareshare.net.au/wp-content/uploads/FareShareLogo-LandscapeSmall.png',
        smallDescription:
            'FareShare rescues food that would otherwise go to waste and cooks it into free nutritious meals for people in need. An estimated five million Australians experienced food insecurity last year while food waste costs our economy an estimated $20 billion.',
        longDescription:
            'FareShare tackles the tragedy head on by rescuing surplus, quality food from supermarkets, wholesalers, farmers and other businesses and cooking it into nutritious meals. In Melbourne, with the help of 1000 regular volunteers, FareShare cooks more than 6,000 free meals a day for charities such as soup vans, homeless shelters, women\u2019s refuges and community food banks. In 2018 FareShare opened a second production kitchen, designed to cook  up to five million meals a year, in Brisbane as part of an exciting collaboration with Foodbank. The new operation effectively doubles FareShare\u2019s social impact, bringing our daily total of cooked meals to around 12,000. FareShare helps avoid food waste and diverts surplus, edible food from landfill. This reduces greenhouse pollution and ensures food produced for humans reaches those who need it most. We are a charity and we rely on the generosity of philanthropic foundations, businesses and individual donors to rescue food and cook meals.',
        addressLine1: '1-7 South Audley St',
        townCity: 'Abbotsford',
        state: 'Victoria',
        postcode: 3067,
        country: 'Australia',
        charityWebsite: 'fareshare.net.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 40002286553,
        charityLegalName: 'JDRF Australia',
        imageURL:
            'https://jdrf.org.au/wp-content/uploads/2019/03/h_lNxVXLqrDqb2kyrixW3lMmUl7n-aBRzJUzyvzD7_8ZeFWFSRrSQ8LCl2i6ted1Sfmt_lDQLryoTFrXHQNBp1lay7Bdxjf2PbcikoFkvwYkvNtBJXVHe1LXmJmetPFG.png',
        smallDescription:
            'JDRF has transformed the understanding of Type 1 Diabetes (T1D). We have been part of every breakthrough in T1D care in the last 40 years. We drive innovation, demand action and stand with everyone facing life with T1D. We know research is the key to destroy T1D.',
        longDescription:
            'Starting in the US in 1970, JDRF began in Australia in 1982 as a small group of parents who believed their children deserved better. Now, millions of people work with and support JDRF in over 20 countries. We connect the best people in every discipline, industry and organization with a single focus on destroying T1D. 40 years of investment in the best researchers has created an exciting pipeline from academic research through to clinical trials and therapies requiring approval and financial support for people to access them. At the heart of JDRF are the 120,000 children and adults in Australia who have been diagnosed with T1D and counting, with 2400 newly diagnosed each year. Our Blue Army extends to the families, carers, teachers and friends of those with T1D and to all those who fight on their behalf, the JDRF team, scientists, researchers, nurses, pharmaceutical companies, parliamentarians, volunteers, corporate partners and donors. We are thankful for every one of them and we are thankful for you. Help change the lives of millions of people living with T1D, those who love them and the communities we all live in. Together, we will create a world without T1D.',
        addressLine1: 'L 4 80-84 Chandos St',
        townCity: 'Naremburn',
        state: 'New South Wales',
        postcode: 2065,
        country: 'Australia',
        charityWebsite: 'https://jdrf.org.au/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 89094189465,
        charityLegalName: 'Jobs Queensland Limited',
        imageURL: 'https://jobsqld.org.au/wp-content/uploads/2017/09/phone-icon.png',
        smallDescription:
            'Training and programs to enhance the skills and employment opportunities of disadvantaged job seekers. Preparing parents to enter the workforce and placing them into employment. Provide employment opportunities for long term unemployed and disadvantaged groups.',
        longDescription:
            'We have a strong track record in obtaining government funding and assistance and this enables us to implement our programs in a holistic manner to work with individuals to improve their skills and knowledge. We also provide additional support services to address issues and barriers that have previously disadvantaged them and hindered their employment opportunities. In 2017, Jobs Queensland expanded to offer both an office in Rockhampton and in Mackay with the aim of building on successes within these communities. Jobs Queensland Limited (JQL) is a local community based not for profit organization in operation since August 2000. Since its inception, JQL has worked to deliver employment and training programs to benefit local job seekers in the Central Queensland Area. Jobs Queensland Limited strives to be a leading not for profit, community based organization providing high quality, flexible and professional services to our diverse clients. Delivering assistance programs with a strong focus on employment and training throughout Rockhampton, Central Queensland and Mackay. Our solid organizational structure and many years of experience are the tools we use to achieve success and continue assist our local communities.',
        addressLine1: 'Level 1, 17 William Street',
        townCity: 'Rockhampton',
        state: 'QLD',
        postcode: 4700,
        country: 'Australia',
        charityWebsite: 'www.jobsqld.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 33107782196,
        charityLegalName: 'Oz Harvest Limited',
        imageURL: 'https://www.underconsideration.com/brandnew/archives/ozharvest_logo_detail.gif',
        smallDescription:
            'OzHarvest is Australia\u2019s leading food rescue organization, collecting quality excess food from commercial outlets and delivering it directly to more than 1300 charities supporting people in need across the country.',
        longDescription:
            'Founded in 2004 by Ronni Kahn AO, after noticing the huge volume of good food going to waste from the hospitality industry, she decided there had to be a better way.  Starting in Sydney with one van \u2013 the first of many donations from Goodman+ Foundation \u2013 she delivered 4,000 meals in the first month. OzHarvest now operates nationally, rescuing over 180 tonnes of food each week from over 3,500 food donors including supermarkets, hotels, airports, wholesalers, farmers, corporate events, catering companies, shopping centres, delis, cafes, restaurants, film and TV shoots and boardrooms. education is crucial to our business to help enable positive change for vulnerable people. Check out OzHarvest\u2019s education programs, NEST and Nourish. Our curriculum-aligned education program FEAST, which is available nationally, inspires primary school students to eat healthy, waste less and be change-makers in their local community. We recently opened Australia\u2019s first rescued food supermarket \u2013 the OzHarvest Market in Sydney, based on a \u2018take what you need, give if you can\u2019 philosophy. And look out for our new OzHarvest Food Truck, available for corporate, community and private functions and helping feed communities in need around Sydney.',
        addressLine1: '46-62 Maddox St',
        townCity: 'Alexandria',
        state: 'New South Wales',
        postcode: 2015,
        country: 'Australia',
        charityWebsite: 'https://www.ozharvest.org',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 89010040914,
        charityLegalName: 'Queensland Positive People Inc.',
        imageURL: 'https://www.qpp.org.au/wp-content/themes/qpp/images/qpp-logo.png',
        smallDescription:
            'Queensland Positive People (QPP) is a peer-based advocacy organization which is committed to actively promoting self-determination and empowerment for all people living with HIV (PLHIV) throughout Queensland.',
        longDescription:
            'The establishment of QPP aligns with state and National HIV policy strategies that recognise HIV prevention, and sustaining improved health outcomes, requires a critical partnership between PLHIV and those responsible for making decisions that affect their access to specialist care, treatment and support.\n\nThis partnership is also recognised under Australia\u2019s endorsement of the United Nations principle of MIPA: that the Meaningful Involvement of PLHIV in program development, implementation and policy-making will improve the relevance, acceptability and effectiveness of the HIV response as they have directly experienced the factors that make individuals and communities vulnerable to HIV.\n\nQPP staff welcome community questions as they relate to our core programs: peer support, health promotion and treatment information, advocacy, and community HIV education and prevention.',
        addressLine1: '21 Manilla St',
        townCity: 'East Brisbane',
        state: 'Queensland',
        postcode: 4169,
        country: 'Australia',
        charityWebsite: 'http://www.qpp.org.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 53046843443,
        charityLegalName: 'Reclink Australia',
        imageURL: 'https://reclink.org/sites/all/themes/custom/reclink_2018/logo.png',
        smallDescription:
            'Reclink Australia provides evidence-based sport and art programs to disadvantaged Australians to create socially inclusive, life-changing opportunities.',
        longDescription:
            'You can help people experiencing disadvantage to lead healthy, fulfilling lives. We\u2019ve been working with communities around Australia for over 25 years and we know that the best way to fight social isolation and disadvantage is to promote participation in local sport, recreation and arts programs. By making a general donation, you\u2019ll be helping to provide pathways to long-term change \u2014 improved health and wellbeing, education and employment outcomes for all participants. We\u2019re experts at delivering sport, recreation and arts programs \u2014 like football, swimming and art programs \u2014 to disadvantaged people across Australia. By donating regularly each month, you too could help provide access for a homeless person to participate in a weekly cricket program, enable a person experiencing mental illness to attend a tai-chi lesson or provide a football program to an entire community.',
        addressLine1: '115B Ferrars Street',
        townCity: 'South Melbourne',
        state: 'VIC',
        postcode: 3205,
        country: 'Australia',
        charityWebsite: 'www.reclink.org',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 65228690068,
        charityLegalName: 'Resolve SBB Trust',
        imageURL: 'https://www.socialventures.com.au/wp-content/themes/sva/assets/img/brand-refresh/sva-logo-full.svg',
        smallDescription:
            'The Resolve Social Benefit Bond is Australia\u2019s first social impact investment aimed at improving mental health outcomes.',
        longDescription:
            'The Resolve Social Benefit Bond (Resolve SBB) provides investors with an opportunity to generate a competitive financial return while improving the lives of people suffering mental health issues in NSW. Investors will be funding the working capital of the Resolve Program, a recovery-orientated community support program which combines a residential service for periodic crisis care integrated psychosocial, medical and mental health support; and a warm line for after-hours support from peers. The Resolve Program will be delivered by Flourish Australia, a highly experienced mental health service provider and a national leader in the employment and support of mental health peer workers. It is anticipated that approximately 530 adults will be supported by the Resolve Program over a seven-year service delivery period. The Resolve Program will support each participant for up to two years, and will be delivered in collaboration with the Nepean Blue Mountains and Western NSW Local health Districts. The Resolve SBB is expected to improve the mental health and wellbeing of participants, while generating significant savings for the NSW Government through a reduction in participants\u2019 utilisation of health and other services, in particular by reducing the number of days spent in hospital. These savings will be shared with Flourish, to fund the delivery of the Resolve Program, and with investors to provide a financial return on their capital.',
        addressLine1: 'L 7 1 Chifley Sq',
        townCity: 'Sydney',
        state: 'New South Wales',
        postcode: 2000,
        country: 'Australia',
        charityWebsite: 'https://www.socialventures.com.au/work/resolve-sbb/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 84140233790,
        charityLegalName: 'Victorian Comprehensive Cancer Centre Ltd',
        imageURL: 'https://www.viccompcancerctr.org/resources/themes/vccc/dist/img/logo.jpg',
        smallDescription:
            'Together, the VCCC alliance partners represent a critical mass of expertise and resources. Our mission is to turn the potential of this into best possible outcomes for Victorian cancer patients.',
        longDescription:
            'The comprehensive cancer centre (CCC) model, established by the US Government, has now been adopted in most developed countries. The Victorian Comprehensive Cancer Centre (VCCC) is Australia\u2019s first comprehensive cancer centre providing a multidisciplinary, integrated approach to cancer research, education and clinical care. The fundamental premise for Victoria is that a comprehensive cancer centre of integrated organizations will gain far greater benefits in cancer more quickly than an individual organization could achieve alone. The VCCC alliance works strategically and collaboratively; integrating cancer research, clinical trials and education to enable and accelerate the translation of scientific evidence into patient and community benefit. Consultation across the alliance organizations, gaining feedback from people working in all aspects of cancer, has been implemented several times to develop broad, strategic frameworks. In addition, representatives from the alliance contribute to the VCCC\u2019s activities and programs through steering committees and working groups.',
        addressLine1: 'L 10 305 Grattan St',
        townCity: 'Melbourne',
        state: 'Victoria',
        postcode: 3000,
        country: 'Australia',
        charityWebsite: 'https://www.viccompcancerctr.org/',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
    {
        abn: 60433691542,
        charityLegalName: 'Vietnam veterans Keith Payne V C Hostel Ltd',
        imageURL: 'https://vietvets.com.au/wp-content/uploads/2019/07/vv-logo-600.jpg',
        smallDescription:
            'Vietnam veterans Keith Payne VC Hostel is a residential aged care community, providing excellent quality of life for our residents. ',
        longDescription:
            'Vietnam veterans Keith Payne VC Hostel has been delivering the highest level of personalised, 24-hour aged care to its residents since 1991. While our heritage is built upon caring for those who served so bravely, we are a community that also welcomes non-veterans to make their home with us. Located only 5-minutes from the ocean in Noraville on the northern end of the NSW Central Coast, surrounded by lush bush surrounds and spacious grounds, the facility provides the most peaceful setting for residents to share their stories with neighbours, family and loved ones. We\u2019re a fully accredited, not-for-profit aged care community that caters for up to 76 residents on either a full-time or temporary respite care basis. Our care team provide 24/7 Registered Nurse access, with our capabilities further increased through the addition of new person centred software that enhances communication, documentation and connection between our staff and residents. Since its establishment, Vietnam veterans has evolved into a multi-purpose residential aged care community. Our residents\u2019 quality of life is top priority. For this reason, we have grown to embrace the whole community through the hosting of lifetime events such weddings, funerals, family occasions and corporate functions.',
        addressLine1: '1 Evans Rd',
        townCity: 'Noraville',
        state: 'New South Wales',
        postcode: 2263,
        country: 'Australia',
        charityWebsite: 'www.vietvets.com.au',
        territoryACT: true,
        territoryNSW: true,
        territoryNT: true,
        territoryQLD: true,
        territorySA: true,
        territoryTAS: true,
        territoryVIC: true,
        territoryWA: true,
        education: true,
        health: true,
        chronicIllness: true,
        disabilities: true,
        homelessness: true,
        unemployment: true,
        veterans: true,
    },
  ];
  